# Generated by Django 2.0.6 on 2018-10-09 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('date_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='TimeSheet',
        ),
    ]
